language: csharp
dist: trusty
sudo: required
mono: none
dotnet: "2.1.4"
script:
  - ./build.sh --quiet verify
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh $NUGET_API_KEY
  on:
    branch: master